name: turnopro_apk
description: Project is an application for businesses related to a barberia.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^0.13.6
  google_fonts: ^4.0.4  
  flutter_native_splash: ^2.3.2
  flutter_launcher_icons: ^0.13.1
  flutter_slidable: ^3.0.0
  animate_do: ^3.0.2
  lottie: ^2.6.0
  
flutter_native_splash:  
  color: "#3F51B5"
  image: "assets/app/splash.png"
  android: true
  ios: true
  
flutter_icons:
  image_path: "assets/app/icon.png" 
  ios: true
  remove_alpha_ios: true
  android: "launcher_icon"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/app/icon-android.png"




dev_dependencies:
  flutter_test:
    sdk: flutter
  get: ^4.6.5
  flutter_lints: ^2.0.0
  


  
flutter:
  uses-material-design: true

  assets:
     - assets/images/profile.png
     - assets/images/pngegg.png
     - assets/images/sprite.png
     - assets/images/image_perfil.jpg
     - assets/images/radial_scale.png
